### ISSUE TITLE
Challenge code field not supplied and library repository records not updating

### ISSUE THREAD

**Issue by theTroi** [susom/redcap-em-giftcard-reward#4] opened 2022-03-25 20:37 UTC
The external module sends an email with the reward URL field when logic is met but does not include the challenge_code field. In addition, the record isn't saving information after an email is sent to a participant/participant clicks on the reward URL to 'claim' it.  Therefore, the next participant received the same reward code due to it not being marked off as claimed.

**Comment by yasukawa** [comment] 2022-03-28 16:46
Are you using version v2.0?  If so, I found a bug and have fixed it.  I submitted a new version to the consortium v2.0.1 just now which should fix the record information not saving.

I have not seen the issue with the challenge code not displaying when it is filled in.  By design, it will not display when empty or when the egift_number is a web address instead of an alphanumeric string.  Can you give me more information on when the challenge code is not displaying.

**Comment by 123andy** [comment] 2024-02-01 02:11
Closing this as non-responsive.

**Closed as completed by 123andy** 2024-02-01 02:11 UTC
